sudo: required
services:
  - docker

before_install:
  - gem install rake
  - gem install bundler
  - gem update bundler
  - docker build -t sunnysingh/docker-react -f Dockerfile.dev .

scripts:
  - docker run sunnysingh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: ""
  bucket_name: ""
  bucket_path: "docker-react"
