sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - gem update bundler
  - docker build -t sunnysingh/docker-react -f Dockerfile.dev .

scripts:
  - docker run sunnysingh/docker-react npm run test -- --coverage

